FROM python:3.12.8-slim

WORKDIR /app

# Устанавливаем зависимости
RUN pip install --no-cache-dir google-auth-oauthlib

# Копируем скрипт
COPY create_token.py .

# Указываем рабочую директорию для сохранения файлов
VOLUME /app/data

# Команда по умолчанию
CMD ["python", "create_token.py"]
