[project]
name = "calendar-agent"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.10"
dependencies = [
    "google-auth-oauthlib>=1.2.2",
    "langchain-google-community>=2.0.10",
    "langchain-ollama>=0.3.10",
]
