help: |
  **Команды**:
  - /auth - аутентификация через Google для доступа календарю.
  - /refresh - пересоздание агента.
  - /help - информация.
start: |
  Данный бот является ИИ-агентом для помощи в составлении расписания.
  Умеет:
  1. Получать и изменять мероприятия в Google Calendar (будьте аккуратны).
  2. Работать с базой данных пропусков.

  *Перед использованием необходимо аутентифицироваться с помощью* /auth.
  Иначе, не будут доступны действия с календарём.

  В базе данных есть сущность Subject, которая представляется полями:
  - `name` - название предмета.
  - `skips` - количество пропусков.
  - `criticality` - критичность предмета: низкая, средняя или высокая.

  Вы можете попросить агента добавить предмет, прибавить или убавить пропуски.
